### ISSUE TITLE
Error using jUnit options

### ISSUE THREAD

**Issue by eddieajau** [jasmine-contrib/grunt-jasmine-node#52]
Grunt file configuration:

``` js
        jasmine_node: {
            options: {
                jUnit: {
                    report: true,
                    savePath : './build/reports/jasmine',
                    useDotNotation: true,
                    consolidate: true
                }
            },
            all: ['spec/']
        },
...
    grunt.registerTask('integrationtest', ['jasmine_node']);
```

Installed

``` sh
└── grunt-jasmine-node@0.2.1 
jasmine-node@1.14.5 node_modules/jasmine-node
├── mkdirp@0.3.5
├── walkdir@0.0.7
├── coffee-script@1.7.1
├── requirejs@2.1.14
├── jasmine-reporters@1.0.0
├── jasmine-growl-reporter@0.0.3 (growl@1.7.0)
└── gaze@0.3.4 (minimatch@0.2.14, fileset@0.1.5)
```

Getting this error running the integration tests:

``` sh
Failed to execute "jasmine.executeSpecsInFolder": TypeError: undefined is not a function
    at Object.jasmine.executeSpecsInFolder (/Users/foo/git/ETLaaS/node_modules/grunt-jasmine-node/node_modules/jasmine-node/lib/jasmine-node/index.js:100:28)
    at Object.<anonymous> (/Users/foo/git/ETLaaS/node_modules/grunt-jasmine-node/tasks/jasmine-node-task.js:96:17)
    at Object.<anonymous> (/Users/foo/git/ETLaaS/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/foo/git/ETLaaS/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/foo/git/ETLaaS/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/foo/git/ETLaaS/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/foo/git/ETLaaS/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/foo/git/ETLaaS/node_modules/grunt/lib/util/task.js:227:11
    at process._tickDomainCallback (node.js:463:13)
    at Function.Module.runMain (module.js:499:11)
```

Setting `report` to `false` allows the tests to run.

Is there a possible configuration problem my end?

**Comment by matmar10** [comment]
I tried out PR #50 and it works for me.
